### ISSUE TITLE
osmium nuggets added when mekanism is installed lack recipe for ingot

### ISSUE THREAD

**Issue by kotoroshinoto** [InfinityRaider/AgriCraft#137]
should have the 3x3 nugget-> ingot recipe, but for some reason it isn't there.

**Comment by kotoroshinoto** [comment]
Might be that I was using an outdated version. I'll update and see if the issue remains.

**Comment by InfinityRaider** [comment]
Definatly not due to versioning, as it's been ages since I changed something about recipe code, I'll fix it.

**Comment by InfinityRaider** [comment]
I can confirm, its happening in my dev env as well, my guess is it's something to do with Osmium not being oredicted correctly.

**Comment by kotoroshinoto** [comment]
It probably ISN"T oredicted correctly. Should I take the liberty of raising that issue with Mekanism devs?

**Comment by InfinityRaider** [comment]
It is registered, I think its being registered too late, but I'm not sure. I'll check my code first

**Comment by BBoldt** [comment]
Just sharing this short minetweaker script for anyone else that comes across this issue before the official fix is out:

```
// Osmium fix
recipes.addShapeless(<Mekanism:Ingot:1>, [<ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>, <ore:nuggetOsmium>]);
recipes.addShapeless(<AgriCraft:nuggetOsmium> * 9, [<ore:ingotOsmium>]);
```

**Comment by BBoldt** [comment]
Hilariously, that script actually causes server crashes whenever someone interacts with the nuggets. 

Do not use.

**Comment by InfinityRaider** [comment]
What, how? Can you give a stacktrace please?

**Comment by BBoldt** [comment]
It was happening on a server a friend was running, I didn't think to get logs as it was something I caused with minetweaker. I suspect it was because I used the oredict osmium ingot, adding the same recipe you add, somehow making things more broken.

Honestly i'm not sure, I just disabled the script.

**Comment by InfinityRaider** [comment]
Adding duplicate recipes shouldn't break stuff afaik

**Comment by InfinityRaider** [comment]
Fixed in rewrite

**Comment by tethlah** [comment]
So I've updated to 2.0.0-0.10.0-a18 and this issue still exists, you can't do anything with the osmium ingots.
