### ISSUE TITLE
Disabling Weeds causes corrupt recipe crash.

### ISSUE THREAD

**Issue by Rader2146** [InfinityRaider/AgriCraft#151]
AgriCraft 1.3.1

Dissabling weeds causes Hardcore Ender Expansion to force a crash due to a "corrupt recipe"

    # set to false if you wish to disable weeds [default: true]
    B:"Enable weeds"=false

Crash Report:
https://gist.github.com/Rader2146/150f4fe2cc7c7d24610f

Lines from fml-client-latest.log reference in the crash report:
[18:07:26] [Client thread/TRACE] [HardcoreEnderExpansion/HardcoreEnderExpansion]: Sending event FMLPostInitializationEvent to mod HardcoreEnderExpansion
[18:07:28] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <null> <= {[minecraft]tile.fence/32767, [minecraft]item.stick/0(ore)}
[18:07:28] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <null> <= {[minecraft]tile.fenceIron/32767, [minecraft]item.stick/0(ore)}
[18:07:28] [Client thread/TRACE] [HardcoreEnderExpansion/HardcoreEnderExpansion]: Sent event FMLPostInitializationEvent to mod HardcoreEnderExpansion

Attempted disabling the hand rake, but it still crashed just the same.

    # When enabled, weeds can only be removed by using this Hand Rake tool [default: true]
    B:"Enable Hand Rake"=false

**Comment by InfinityRaider** [comment]
Can you report this to the HEE guys? I don't see what I can do about this.

**Comment by chylex** [comment]
Maybe don't register recipes with items that don't exist >.> that's a great way to get some random world corruption when crafting.

**Comment by InfinityRaider** [comment]
I'm not registering any recipes with items that dont exist

**Comment by InfinityRaider** [comment]
Okay it appears I am, sorry fixed.

**Comment by chylex** [comment]
Yea, don't worry you aren't the first person to fall into the trap of configurable items.

**Comment by cocopuffs99** [comment]
Getting the same crash with AgriCraft 1.7.10 1.3.1:

 Caught exception from HardcoreEnderExpansion
java.lang.RuntimeException: A defective recipe has crashed the game! Another mod is creating recipes with non-existent blocks or items, which is a serious error that will cause item or even world loss when crafting these recipes. Corrupted recipes have been saved in the log with tag [HEE-ORB], please try to find which mod they belong to and report them to the respective modder. Then enable the 'overrideRemoveBrokenRecipes' option in Hardcore Ender Expansion and the game will start.
        at net.minecraft.item.ItemStack.func_77984_f(ItemStack.java:197) ~[add.class:?]
        at net.minecraft.item.ItemStack.func_77951_h(ItemStack.java:207) ~[add.class:?]

--

[06:30:16] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <null> <= {[minecraft]tile.fence/32767, [minecraft]item.stick/0(ore)}
[06:30:16] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <null> <= {[minecraft]tile.fenceIron/32767, [minecraft]item.stick/0(ore)}
[06:30:17] [Client thread/TRACE] [HardcoreEnderExpansion/HardcoreEnderExpansion]: Sent event FMLPostInitializationEvent to mod HardcoreEnderExpansion

FML Log (refers to HEE-ORB): http://pastebin.com/87233H7g
full FTB Log (HEE-ORB- corrupted recipe): http://tny.cz/e77af372

**Comment by chylex** [comment]
Some info got lost, there's supposed to be <null> in front of <=. Anyways, just got a notification about it.

**Comment by InfinityRaider** [comment]
Ye this has been fixed already.

**Comment by cocopuffs99** [comment]
Hmm, still getting the error; Maybe its from another mod?  Any idea what mod is using this recipe?  I can't find out which mod from the FML log

[HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]tile.fence/32767, [minecraft]item.stick/0(ore)}
[12:13:32] [Client thread/ERROR] [HardcoreEnderExpansion/HardcoreEnderExpansion]: [HEE-ORB] Corrupted shaped ore recipe: <error:null> <= {[minecraft]tile.fenceIron/32767, [minecraft]item.stick/0(ore)}

**Comment by InfinityRaider** [comment]
Its fixed for the next version which hasn't been released as of yet

**Comment by cocopuffs99** [comment]
@InfinityRaider Oh! Ok great thanks =) Any chance I can try out one of the dev builds?  I can send in bug reports.  Thanks for an amazing mod!

**Comment by InfinityRaider** [comment]
Probably once fix the Magical Crops 4 crashing

**Comment by Mrbysco** [comment]
Has it been released yet?

**Comment by InfinityRaider** [comment]
no sry
